---

- dynamic_defaults:
    hostvars: '{{ hostvars[inventory_hostname] }}'
    defaults: '{{ bash_dynamic_defaults }}'
    must_match: yes
  tags: [bash, always]

- block:
    - name: Configure BASH
      template:
        src: '{{ bash_config_file }}'
        dest: '{{ bash_config_filename }}'
        mode: '644'

    - name: Configure BASH user profile skeleton
      template:
        src: '{{ bash_user_config_file }}'
        dest: /etc/skel/.bashrc
        mode: '644'

    - name: Configure BASH users profile
      template:
        src: '{{ bash_user_config_file }}'
        dest: '{{ ansible_user_dir }}/.bashrc'
        mode: '644'
      become_user: '{{ item }}'
      loop: '{{ bash_users }}'
  become: yes
  tags: [bash, config]
